[project]
authors = ["Liel Amar <liel@lielamar.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "UnsponseredGoogle"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=22.9.0,<23"
